version: "3.9"

services:
  back-end: 
    container_name: e_commerce_back_end
    build: .
    ports:
      - "3000:3000"
    env_file: 
      - .env
    depends_on:
      - postgres

  postgres:
    container_name : data_base
    image : postgres:15
    restart : always
    env_file:
      - .env.postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes: 
  postgres_data